steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mentalia:latest'
      - '.'
    dir: '.'  # Força raiz do repo

images:
  - 'gcr.io/$PROJECT_ID/mentalia:latest'
timeout: 600s  # 10 min max
